name: CI/CD

on:
  push:
    branches:
      - dev
    tags:
      - 'v*.*.*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Lint
        run: |
          docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:latest golangci-lint run -v --timeout=3m

  init-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Environment Variables
        id: values
        run: |
          if [[ $GITHUB_REF =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            export TAG=$GITHUB_REF_NAME
          else
            export TAG=$GITHUB_REF_NAME.${GITHUB_SHA::7}
          fi
          IMAGE=najib007/ltp-api:$TAG
          echo "::set-output name=TAG::${TAG}"
          echo "::set-output name=IMAGE::${IMAGE}"
          
    outputs:
      TAG: ${{ steps.values.outputs.TAG }}
      IMAGE: ${{ steps.values.outputs.IMAGE }}

  build-and-push:
    needs: init-variables
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_SECRET_TOKEN }} | docker login -u nologin --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ needs.init-variables.outputs.IMAGE }} -f Dockerfile --build-arg TAG=${{ needs.init-variables.outputs.TAG }} .
          docker push ${{ needs.init-variables.outputs.IMAGE }}


